### ISSUE TITLE
清空 CC 包络点出错

### ISSUE THREAD

**Issue by xris1658** [EchoInMirror/EchoInMirror#13]
# 复现
- 新建轨道；
- 在轨道上新建片段；
- 删除 CC1 的两个包络点。

# 错误信息
```
Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302)
	at java.base/java.util.Objects.checkIndex(Objects.java:385)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at com.eimsound.daw.components.EnvelopeEditorKt.getSelectedPoint-EPk0efs(EnvelopeEditor.kt:114)
	at com.eimsound.daw.components.EnvelopeEditorKt.access$getSelectedPoint-EPk0efs(EnvelopeEditor.kt:1)
	at com.eimsound.daw.components.EnvelopeEditor$Editor$2$2$1$1.invokeSuspend(EnvelopeEditor.kt:216)
...
```

**Comment by ShirasawaSama** [comment]
主要还是因为现在还不完善，包络功能得等接下来弄完midi导入才进行细调。这两天的目标就是midi导入相关，非常感谢你的测试！

**Comment by ShirasawaSama** [comment]
Fixed in next push.
