### ISSUE TITLE
None of the plugins can be added properly

### ISSUE THREAD

**Issue by xris1658** [EchoInMirror/EchoInMirror#5]
## Reproduce

 Trying to scan plugins (both VST2 and VST3). All plugins will be excluded.

## Error Message
The following message is the error message generated while scanning one of my plugins.
```
com.fasterxml.jackson.module.kotlin.MissingKotlinParameterException: Instantiation of [simple type, class cn.apisium.eim.api.processor.NativeAudioPluginDescription] value failed for JSON property identifier due to missing (therefore NULL) value for creator parameter identifier which is a non-nullable type
 at [Source: (String)"[{"name": "BL Gain12", "descriptiveName": "BL Gain12", "pluginFormatName": "VST3", "category": "Fx|Dynamics", "manufacturerName": "BlueLab", "version": "5.0.4", "fileOrIdentifier": "C:\\Program Files\\Common Files\\VST3\\Blue-Lab\\BL-Gain12.vst3", "lastFileModTime": 1580315146000, "lastInfoUpdateTime": 1672843058851, "deprecatedUid": 336595253, "uniqueId": -23082037, "isInstrument": false, "hasSharedContainer": false, "hasARAExtension": false}]"; line: 1, column: 447] (through reference chain: java.util.ArrayList[0]->cn.apisium.eim.api.processor.NativeAudioPluginDescription["identifier"])
	at com.fasterxml.jackson.module.kotlin.KotlinValueInstantiator.createFromObjectWith(KotlinValueInstantiator.kt:84)
	at com.fasterxml.jackson.databind.deser.impl.PropertyBasedCreator.build(PropertyBasedCreator.java:202)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeUsingPropertyBased(BeanDeserializer.java:519)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1405)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:352)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:359)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323)
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4730)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3677)
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3660)
	at cn.apisium.eim.impl.processor.NativeAudioPluginFactoryImpl$scan$4$1$1.invokeSuspend(NativeAudioPluginImpl.kt:212)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```
Seems like `identifier` needed by `cn.apisium.eim.api.processor.NativeAudioPluginDescription` is missing from the JSON string that the program generated.

This might be helpful: [MissingKotlinParameterException: due to missing (therefore NULL) value for creator parameter … which is a non-nullable type · Issue #87 · FasterXML/jackson-module-kotlin](https://github.com/FasterXML/jackson-module-kotlin/issues/87)

**Comment by ShirasawaSama** [comment]
因为现在项目每天都还在开发，所以api可能时不时会变。

这是因为EIMHost更新了，重新下载最新的替换即可

https://github.com/EchoInMirror/EIMHost/releases/tag/1.0.3

**如果你愿意一同开发，可以加入我们**
